Updated requirements.txt with zstd module
JDASoftwareGroup/kartothek pull request #393
Opened 2021-01-19 06:04 UTC by imkumarg

# Description:

The _zmsgpack.py (kartothek.core.cube) uses zstd module for the compressor and decompressor technique. I have updated the requirements.txt with the module name.

- [ ] Closes The build failure of https://travis-ci.com/github/JDASoftwareGroup/kartothek_hive_integration_test/builds/213539032

2021-01-19 08:23 UTC, fjetter requested changes
There are two packages for the zstd compression lib in python

https://github.com/indygreg/python-zstandard

and 

https://github.com/sergey-dryabzhinsky/python-zstd

and we're using the first one. Installing both can have non trivial side effects.

The release notes of zstandard==0.15.0 mention already that some modules are no longer available in the `zstandard` module any longer but rather in `zstd` therefore I would like to change the import in our module accordingly instead of adding a redundant dependency

See also https://github.com/JDASoftwareGroup/kartothek/pull/392

2021-01-19 09:02 UTC, imkumarg commented
So instead, I have to modify the usage of `zstd` accordingly in the codebase.

2021-01-19 10:06 UTC, hoffmann commented
@fjetter  is it an option to downpin zstandard in this tests until https://github.com/JDASoftwareGroup/kartothek/pull/392 is fixed?

2021-01-19 10:11 UTC, lr4d commented
From the [zstandard docs](https://python-zstandard.readthedocs.io/en/latest/projectinfo.html)
> There will be some backwards incompatible changes before 1.0, probably in the 0.9 release. This may involve renaming the main module from zstd to zstandard and renaming various types and methods. Pin the package version to prevent unwanted breakage when this change occurs!

2021-01-19 10:44 UTC, lr4d commented
I think the easiest way forward here is using this commit [`d8f4c22` (#392)](https://github.com/JDASoftwareGroup/kartothek/pull/392/commits/d8f4c22a67725c5907ab07bd858d42d7956738f3)
Otherwise, we can also downpin zstandard.

2021-01-19 10:51 UTC, imkumarg commented
> I think the easiest way forward here is using this commit [`d8f4c22` (#392)](https://github.com/JDASoftwareGroup/kartothek/pull/392/commits/d8f4c22a67725c5907ab07bd858d42d7956738f3)
> Otherwise, we can also downpin zstandard.

Yes  I think too, we can use this commit [`d8f4c22` (#392)]

2021-01-19 10:55 UTC, fjetter commented
Haven't tried downpinning and I do not know why tests do not detect this. However, I do not feel comfortable with installing both zstandard libs. I think reusing https://github.com/JDASoftwareGroup/kartothek/pull/392/commits/d8f4c22a67725c5907ab07bd858d42d7956738f3 is the proper way to go. The other PR is also supposed to deal with the doc build issues since the doc builds are also failing for some other reason

2021-01-19 11:21 UTC, lr4d commented
> I do not know why tests do not detect this

@imkumarg Could you include a test for this so that the test would fail before applying  d8f4c22 (#392) and would pass afterwards?

2021-01-20 09:51 UTC, lr4d commented
Looks good. Please add a changelog entry

2021-01-20 09:56 UTC, fjetter approved these changes

2021-01-20 10:04 UTC, imkumarg commented
> Looks good. Please add a changelog entry

Sure I will make the changes.

2021-01-20 10:44 UTC, dhumil-agarwal-by approved these changes
Looks good.

2021-01-20 10:50 UTC, lr4d commented
We can merge this now to fix the issue downstream, but I would still like to see a test for this so that we don't run into this or a similar issue next time.

2021-01-20 10:54 UTC, lr4d commented
Ah, I just figured out why we weren't seeing this in our CI: zstandard is available up to 0.15.1 on PyPI but only up to 0.14.1 on conda-forge (what we're using in our CI)

2021-01-20 10:56 UTC, merged

2021-01-22 21:47 UTC, xhochy commented
The conda package has been updated, would be nice to get people fix this when I don't have the time ;)

2021-01-25 08:38 UTC, xhochy commented
Can we have a release with this fix?